### ISSUE TITLE
Download link not appearing

### ISSUE THREAD

**Issue by flarn2006** [0x000011b/characterai-dumper#1]
I'm using Greasemonkey on Firefox 106.0.3. I go to the saved chats page, but the Download link doesn't appear. I know that the script is running though, because I see this in the console:

![tmp r7jnDqoWpt](https://user-images.githubusercontent.com/687313/213579544-645d153b-0bc6-4f99-aaf3-2971a13b877e.png)

**Comment by 0x000011b** [comment]
That's weird. Just gave it a shot on my end in case they changed the API around but it still seems fine.

Just confirming: you're on a URL that looks like `https://beta.character.ai/histories?char={{ SOME_ID_HERE }}`, right? If so, can you try giving it a shot with ViolentMonkey? It's what I just used to test.

**Comment by flarn2006** [comment]
Yes, I am on a URL which fits that pattern. I just tried with ViolentMonkey and saw no difference.

**Comment by 0x000011b** [comment]
If you look at the Network tab, do you see these 2 requests being made when you load up the Saved Chats page?

<img width="392" alt="Screen Shot 2023-01-19 at 20 48 34" src="https://user-images.githubusercontent.com/121980126/213590585-45102e24-81d4-416c-83cb-18ebd4bd4bcb.png">

**Comment by flarn2006** [comment]
Yes, and they are both succeeding.

**Comment by 0x000011b** [comment]
That's really strange. Then, for whatever reason, XHook isn't calling my code to handle the intercepted requests. If you're more dev-inclined, you can set up some debugger breakpoints inside this callback to try and figure out what's going on: https://github.com/0x000011b/characterai-dumper/blob/f008b3fa5ce450a5433a788400c9d1b51961cd08/characterai-dumper.user.js#L173

**Comment by flarn2006** [comment]
I set a breakpoint on that line and it doesn't seem to have triggered.
![image](https://user-images.githubusercontent.com/687313/213788894-95d1ab15-22d6-4487-bc39-a930bc0f9166.png)

**Comment by k0ala991** [comment]
I'm having this issue too. One thing I can add is that the drop down list for violent monkey that shows the enabled scripts for this tab does not show this script at all when on the chats page, even though it is enabled in the scripts dashboard.

**Comment by flarn2006** [comment]
I just tried it in Violentmonkey on Chromium and it worked there.

**Comment by 0x000011b** [comment]
> I set a breakpoint on that line and it doesn't seem to have triggered. ![image](https://user-images.githubusercontent.com/687313/213788894-95d1ab15-22d6-4487-bc39-a930bc0f9166.png)

Yeah, at that point I'm not sure there's much I can do. XHook seems to be injected correctly, I call it to register the request intercepts and it simply doesn't call it when the requests happen, according to the logs you've sent.

> I just tried it in Violentmonkey on Chromium and it worked there.

Noted. Thanks, I'll add that to the README as a suggestion.

> I'm having this issue too. One thing I can add is that the drop down list for violent monkey that shows the enabled scripts for this tab does not show this script at all when on the chats page, even though it is enabled in the scripts dashboard.

Strange, given that I attempt to inject the userscript for any page on the domain:

https://github.com/0x000011b/characterai-dumper/blob/f008b3fa5ce450a5433a788400c9d1b51961cd08/characterai-dumper.user.js#L4

Possibly just a visual bug?

**Comment by k0ala991** [comment]
I tried it again this morning, and it worked. With no change on my part, not even a browser restart since last night. I'm wondering if it was something on their end.

**Comment by AlbiuxGeek** [comment]
Hello! I'm also having issues with the Download link not appearing. I use Waterfox (a fork of Firefox) where I have a lot of extensions and thought one might be the issue (tried running the scrip with Tampermonkey) so I ended downloading Chromium as someone suggested here and installed ViolentMonkey, is the only thing running on it as it is a clean install and still can't get the button to show. Sadly I'm not that tech savvy and programming is a nightmare to me lol but I'm willing to learn what to do (Yes I am in the "histories?char=random numbers an letters here" page)

EDIT: Well, Every character I talked to but one displays now the button on Chromium with Violentmonkey... That is curious, if I may say. On Waterfox I can't get any to show the link still.

**Comment by GoldenGreninja75** [comment]
Hey so I know this help area is probably dead, but I just need help. I am using ViolentMonkey with the Ai Dump script. Although the script seems to be working just fine, the download never shows up. Yes, I am on beta.character.ai/histories (number id here). Ive tried using firefox and chromnium as from what Ive seen, they seem to work. I got the script and ViolentMonkey and tried to use it, but same thing. No download link. May someone please help me? I'm pretty new to all of this so it would be an absolute blessing, thanks!
![image](https://user-images.githubusercontent.com/131818553/234410405-d4d5f058-4a34-4875-bc89-d01be5818707.png)
![image](https://user-images.githubusercontent.com/131818553/234410681-db8c62c1-8db7-4842-bc8e-132f4a93a8c6.png)

By the way, the messages are of me wanting see how bad the filter is lmao

**Comment by GoldenGreninja75** [comment]
Hey so I know this help area is probably dead, but I just need help. I am using ViolentMonkey with the Ai Dump script. Although the script seems to be working just fine, the download never shows up. Yes, I am on beta.character.ai/histories (number id here). Ive tried using firefox and chromnium as from what Ive seen, they seem to work. I got the script and ViolentMonkey and tried to use it, but same thing. No download link. May someone please help me? I'm pretty new to all of this so it would be an absolute blessing, thanks!
![image](https://user-images.githubusercontent.com/131818553/234414300-91f2b91e-0372-46b7-a1c2-6a4c2fd0da78.png)
![image](https://user-images.githubusercontent.com/131818553/234414529-61edc0aa-4dc1-4e9f-81fe-8017c6a576cd.png)
