### ISSUE TITLE
Download Link not Appearing on Long Chat

### ISSUE THREAD

**Issue by KenjiIchijou** [0x000011b/characterai-dumper#2]
I started using beta.ai about a week ago, before all of the hypocritical stuff went on. I, like many people finding their way to this bit right here, want to save my personal character files for re-use in the alternatives. I like how my little story has gone so far and would like to continue it. 

The issue: download link doesn't appear. I think the issue might be related to it being a 1900~ish word chat because I tried it with a far smaller chat of like 15 messages and the link came up almost immediately. Any help would be appreciated. I am using Tampermonkey 4.18.1 on Google Chrome. I am extremely new to all of this, so patience is appreciated.

**Comment by 0x000011b** [comment]
> I think the issue might be related to it being a 1900~ish word chat because I tried it with a far smaller chat of like 15 messages and the link came up almost immediately.

There's people successfully exporting chats with over 78k words, so that's pretty unlikely.

Can you look at the dev console (F12 usually brings it up), see if there's any relevant errors when you go to the Saved Chats page?

**Comment by KenjiIchijou** [comment]
Sorry for delay. Yes, it says: 
main.a2deb14c.js:2 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
l @ main.a2deb14c.js:2
main.a2deb14c.js:2 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
xM @ main.a2deb14c.js:2
main.a2deb14c.js:2 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
value @ main.a2deb14c.js:2
userscript.html?name=CharacterAI%2520Dumper.user.js&id=5ad3f4ad-d816-441c-a6b9-e3d995673a2b:15 [CharacterAI Dumper v1.4] Injecting XHook to intercept XHR/AJAX calls.
about:blank:1          Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
userscript.html?name=CharacterAI%2520Dumper.user.js&id=5ad3f4ad-d816-441c-a6b9-e3d995673a2b:15 [CharacterAI Dumper v1.4] Done! Configuring intercepts.
manifest.json:1 Manifest: property 'start_url' ignored, should be same origin as document.
userscript.html?name=CharacterAI%2520Dumper.user.js&id=5ad3f4ad-d816-441c-a6b9-e3d995673a2b:15 [CharacterAI Dumper v1.4] Got character info for RWBY RPG, caching...
userscript.html?name=CharacterAI%2520Dumper.user.js&id=5ad3f4ad-d816-441c-a6b9-e3d995673a2b:15 [CharacterAI Dumper v1.4] Got chat histories for Kenji-Ichijou, caching...

**Comment by KenjiIchijou** [comment]
I have no idea how to resume it.

**Comment by samhcheng** [comment]
same problem

the success one

[CharacterAI Dumper v1.4] Got character info for {{bot_name, not id}}, caching...
[CharacterAI Dumper v1.4] Got all the data for {{bot_name, not id}}, creating download link.
[CharacterAI Dumper v1.4] If it doesn't show up, here's the data: ....(a lot)

the failer one

[CharacterAI Dumper v1.4] Got character info for {{bot_name, not id}}, caching...
Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
[CharacterAI Dumper v1.4] Got chat histories for {{user_name}}, caching...
(then it just stops here.)

both have
info/ 
histories/
in Network tab

**Comment by KenjiIchijou** [comment]
Yeah, and the weirdest thing is it works fine on other characters just not this one (which is a bit of a pisser because it's the only one I really want)
