### ISSUE TITLE
Any idea how one might export a room conversation?

### ISSUE THREAD

**Issue by superthrowawayman** [0x000011b/characterai-dumper#6]
I have a long chat that I started as a room rather than a one on one chat, even though there's only one bot in it. Wanted to test out rooms to see if there any differences, but because of that there is no option to view saved chats.

I tried changing the "chat" to "histories" in the url, but I just got an endless loading screen.

Help?

**Comment by 0x000011b** [comment]
Unfortunately that's not supported by the userscript. Unlike individual characters, there's no place where you can fetch the entire conversation history all at once (like you found out), so implementing this would be significantly trickier.

I'm open to reviewing PRs regarding this, but I don't have any plans of implementing it myself at the moment.
